version: 1

trail:
  artifacts:
    - name: dashboard
      attestations:
        - name: lint
          type: generic
        - name: pull-request
          type: pull_request
        - name: snyk-scan
          type: snyk
