version: 1

trail:
  attestations:
    - name: pull-request
      type: pull_request
  artifacts:
    - name: dashboard
      attestations:
        - name: rubocop-lint
          type: generic
        - name: snyk-code-scan
          type: snyk
        - name: snyk-container-scan
          type: snyk
        - name: sonarcloud-scan
          type: sonar
        - name: unit-test
          type: junit
        - name: unit-test-coverage
          type: generic
