version: 1

trail:
  artifacts:
    - name: dashboard
      attestations:
        - name: lint
          type: generic
        - name: pull-request
          type: pull_request
        - name: snyk-code-scan
          type: snyk
        - name: snyk-container-scan
          type: snyk
