AllCops:
  NewCops: enable
  Exclude:
    - test/**/*

Lint/IneffectiveAccessModifier:
  Exclude:
    - source/server/app/app_base.rb

Metrics/AbcSize:
  Exclude:
    - source/server/app/helpers/td_gapper.rb
    - source/server/app/helpers/gatherer.rb
    - source/server/app/helpers/avatars_progress.rb

Metrics/BlockLength:
  Exclude:
    - source/server/app/app_base.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - source/server/app/helpers/td_gapper.rb
    - source/server/app/helpers/avatars_progress.rb

Metrics/MethodLength:
  Exclude:
    - source/server/app/helpers/td_gapper.rb
    - source/server/app/helpers/gatherer.rb
    - source/server/app/helpers/avatars_progress.rb
    - source/server/app/app.rb

Metrics/PerceivedComplexity:
  Exclude:
    - source/server/app/helpers/td_gapper.rb
    - source/server/app/helpers/avatars_progress.rb

Naming/MethodParameterName:
  Exclude:
    - source/server/app/helpers/td_gapper.rb
    - source/server/app/app_base.rb

Style/CaseEquality:
  Exclude:
    - source/client/code/app_base.rb
    - source/server/config/config.ru
    - source/server/app/app_base.rb


Style/Documentation:
  Exclude:
    - source/**/*.rb
