AllCops:
    NewCops: enable

Layout/LineLength:
  Exclude:
    - test/simplecov_formatter_json.rb
    - test/data/cyber-dojo/kata_test_data.rb

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - test/server/check_test_metrics.rb

Layout/SpaceInsideReferenceBrackets:
  Exclude:
    - test/server/check_test_metrics.rb

Lint/IneffectiveAccessModifier:
  Exclude:
    - source/server/app/app_base.rb

Metrics/AbcSize:
  Exclude:
    - test/simplecov_formatter_json.rb
    - test/id58_test_base.rb
    - test/server/check_test_metrics.rb
    - source/server/app/helpers/td_gapper.rb
    - source/server/app/helpers/gatherer.rb
    - source/server/app/helpers/avatars_progress.rb

Metrics/BlockLength:
  Exclude:
    - test/server/td_gapper_test.rb
    - source/server/app/app_base.rb

Metrics/ClassLength:
  Exclude:
    - test/server/td_gapper_test.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - test/id58_test_base.rb
    - source/server/app/helpers/td_gapper.rb
    - source/server/app/helpers/avatars_progress.rb

Metrics/ModuleLength:
  Exclude:
    - test/data/cyber-dojo/kata_test_data.rb

Metrics/MethodLength:
  Exclude:
    - test/id58_test_base.rb
    - test/slim_json_reporter.rb
    - test/simplecov_formatter_json.rb
    - test/data/cyber-dojo/kata_test_data.rb
    - test/server/check_test_metrics.rb
    - source/server/app/helpers/td_gapper.rb
    - source/server/app/helpers/gatherer.rb
    - source/server/app/helpers/avatars_progress.rb

Metrics/PerceivedComplexity:
  Exclude:
    - source/server/app/helpers/td_gapper.rb
    - source/server/app/helpers/avatars_progress.rb

Naming/MethodName:
  Exclude:
    - test/data/cyber-dojo/kata_test_data.rb

Naming/MethodParameterName:
  Exclude:
    - test/id58_test_base.rb
    - source/server/app/helpers/td_gapper.rb
    - source/server/app/app_base.rb

Naming/VariableNumber:
  Exclude:
    - test/data/cyber-dojo/kata_test_data.rb

Security/Eval:
  Exclude:
    - test/server/check_test_metrics.rb

Style/CaseEquality:
  Exclude:
    - test/id58_test_base.rb
    - source/client/code/app_base.rb
    - source/server/config/config.ru
    - source/server/app/app_base.rb

Style/ClassAndModuleChildren:
  Exclude:
    - test/slim_json_reporter.rb

Style/ClassVars:
  Exclude:
    - test/id58_test_base.rb

Style/Documentation:
  Exclude:
    - test/slim_json_reporter.rb
    - test/simplecov_formatter_json.rb
    - test/id58_test_base.rb
    - test/server/test_base.rb
    - test/server/td_gapper_test.rb
    - test/server/gather_test.rb
    - test/server/avatars_progress_test.rb
    - test/data/cyber-dojo/kata_test_data.rb
    - source/**/*.rb

Style/DocumentDynamicEvalDefinition:
  Exclude:
    - test/server/check_test_metrics.rb

Style/EvalWithLocation:
  Exclude:
    - test/server/check_test_metrics.rb

Style/FormatString:
  Exclude:
    - test/server/check_test_metrics.rb

Style/FormatStringToken:
  Exclude:
    - test/id58_test_base.rb
    - test/server/check_test_metrics.rb

Style/TrailingCommaInArrayLiteral:
  Exclude:
    - test/server/check_test_metrics.rb
