#!/bin/bash -Eeu

create_docker_compose_yml()
{
  echo_docker_compose_yml > ${ROOT_DIR}/docker-compose.yml
}

echo_docker_compose_yml()
{
cat <<-EOF
# This file was auto-generated by .../sh/echo_docker_compose_yml.sh
# It is used by .../sh/augmented_docker_compose.sh

version: '3.7'

services:

  nginx:
    build:
      context: source/nginx_stub
    container_name: test_dashboard_nginx
    depends_on:
      - client
    image: cyberdojo/nginx_dashboard_stub
    ports: [ "${CYBER_DOJO_NGINX_PORT}:${CYBER_DOJO_NGINX_PORT}" ]
    user: root

  client:
    image: $(client_image):\${COMMIT_TAG}
    user: $(client_user)
    build:
      args: [ COMMIT_SHA ]
      context: source/client
    container_name: $(client_container)
    depends_on:
      - server
    env_file: [ .env ]
    ports: [ "$(client_port):$(client_port)" ]
    read_only: true
    restart: "no"
    tmpfs: /tmp
    volumes:
      - ./source/client:/app:ro
      - ./test:/test:ro

  server:
    image: $(server_image):\${COMMIT_TAG}
    user: $(server_user)
    build:
      args: [ COMMIT_SHA ]
      context: source/server
    container_name: $(server_container)
    depends_on:
      - differ
      - saver
    env_file: [ .env ]
    ports: [ "$(server_port):$(server_port)" ]
    read_only: true
    restart: "no"
    tmpfs: /tmp
    volumes:
      - ./source/server:/app:ro
      - ./test:/test:ro
EOF
}
