name: Main

on:
  push:
    branches:
      - main

env:
  KOSLI_DRY_RUN: ${{ vars.KOSLI_DRY_RUN }}
  KOSLI_HOST: ${{ vars.KOSLI_HOST }}          # https://app.kosli.com
  KOSLI_ORG: ${{ vars.KOSLI_ORG }}            # cyber-dojo
  KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
  KOSLI_FLOW: ${{ vars.KOSLI_FLOW }}          # dashboard

jobs:

  variables:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.vars.outputs.image_tag }}
    steps:
    - name: Prepare
      id: vars
      run: echo "image_tag=$(echo $GITHUB_SHA | head -c7)" >> ${GITHUB_OUTPUT}

  create-kosli-flow:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Kosli CLI
        uses: kosli-dev/setup-cli-action@v2
        with:
          version: ${{ vars.KOSLI_CLI_VERSION }}

      - name: Create Kosli Flow
        run:
          kosli create flow ${{ env.KOSLI_FLOW }} 
            --description="UX for a group practice dashboard" 
            --template=artifact,snyk-scan,lint,pull-request

#    uses: ./.github/workflows/sub_create_kosli_flow.yml
#    secrets:
#      KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}

  build-image:
    needs: [variables]
    uses: ./.github/workflows/sub_build_image.yml
    secrets:
      KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
    with:
      IMAGE_TAG: ${{ needs.variables.outputs.image_tag }}

  test:
    needs: [variables, create-kosli-flow, build-image]
    uses: ./.github/workflows/sub_test.yml
    secrets:
      KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    with:
      IMAGE_TAG: ${{ needs.variables.outputs.image_tag }}

  sdlc-gate:
    needs: [variables, test]
    uses: ./.github/workflows/sub_sdlc_gate.yml
    secrets:
      KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
    with:
      IMAGE_TAG: ${{ needs.variables.outputs.image_tag }}

  approve-deployment-to-beta:
    needs: [variables, sdlc-gate]
    uses: ./.github/workflows/sub_approve_deployment.yml
    secrets:
      KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
    with:
      KOSLI_ENVIRONMENT: aws-beta
      IMAGE_TAG: ${{ needs.variables.outputs.image_tag }}

  deploy-to-beta:
    needs: [variables, approve-deployment-to-beta]
    uses: ./.github/workflows/sub_deploy_to_beta.yml
    with:
      IMAGE_TAG: ${{ needs.variables.outputs.image_tag }}

  approve-deployment-to-prod:
    needs: [variables, deploy-to-beta]
    uses: ./.github/workflows/sub_approve_deployment.yml
    secrets:
      KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
    with:
      KOSLI_ENVIRONMENT: aws-prod
      IMAGE_TAG: ${{ needs.variables.outputs.image_tag }}

  deploy-to-prod:
    needs: [variables, approve-deployment-to-prod]
    uses: ./.github/workflows/sub_deploy_to_prod.yml
    with:
      IMAGE_TAG: ${{ needs.variables.outputs.image_tag }}
