name: Reports to https://staging.app.kosli.com

on:
  push:
    branches:
      - main

env:
  KOSLI_DRY_RUN: ${{ vars.KOSLI_DRY_RUN }}
  KOSLI_HOST: ${{ vars.KOSLI_HOST_STAGING }}  # https://staging.app.kosli.com
  KOSLI_ORG: ${{ vars.KOSLI_ORG }}            # cyber-dojo
  KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN_STAGING }}
  KOSLI_FLOW: ${{ vars.KOSLI_FLOW }}          # dashboard

jobs:

  variables:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.vars.outputs.image_tag }}
      kosli_host: ${{ steps.vars.outputs.kosli_host }}
      kosli_org: ${{ steps.vars.outputs.kosli_org }}
    steps:
    - name: Prepare
      id: vars
      run: |
        echo "image_tag=$(echo $GITHUB_SHA | head -c7)" >> ${GITHUB_OUTPUT}
        echo "kosli_host=${{ env.KOSLI_HOST }}"         >> ${GITHUB_OUTPUT}
        echo "kosli_org=${{ env.KOSLI_ORG }}"           >> ${GITHUB_OUTPUT}        
        echo "IMAGE_TAG=$(echo $GITHUB_SHA | head -c7)" >> ${GITHUB_ENV}

  create-kosli-flow:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Kosli CLI
        uses: kosli-dev/setup-cli-action@v2
        with:
          version: ${{ vars.KOSLI_CLI_VERSION }}

      - name: Create Kosli Flow
        run:
          kosli create flow ${{ env.KOSLI_FLOW }} 
            --description="UX for a group practice dashboard" 
            --template=artifact,snyk-scan,lint,pull-request

  wait-for-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Wait for image to be built in main.yml
        run:
          ./sh/wait_for_image.sh

  test:
    needs: [variables, create-kosli-flow, wait-for-image]
    uses: ./.github/workflows/sub_test.yml
    secrets:
      KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN_STAGING }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    with:
      KOSLI_HOST: ${{ needs.variables.outputs.kosli_host }}
      KOSLI_ORG: ${{ needs.variables.outputs.kosli_org }}
      IMAGE_TAG: ${{ needs.variables.outputs.image_tag }}

  sdlc-control-gate:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Setup Kosli CLI
        uses: kosli-dev/setup-cli-action@v2
        with:
          version: ${{ vars.KOSLI_CLI_VERSION }}

      - name: Kosli SDLC gate to short-circuit-the-flow
        run: |
          IMAGE_NAME=cyberdojo/${{ env.KOSLI_FLOW }}:${{ env.IMAGE_TAG }}          
          docker pull ${IMAGE_NAME}
          kosli assert artifact ${IMAGE_NAME} \
            --artifact-type=docker          

  approve-deployment-to-beta:
    needs: [variables, sdlc-control-gate]
    uses: ./.github/workflows/sub_approve_deployment.yml
    secrets:
      KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN_STAGING }}
    with:
      KOSLI_HOST: ${{ needs.variables.outputs.kosli_host }}
      KOSLI_ORG: ${{ needs.variables.outputs.kosli_org }}
      KOSLI_ENVIRONMENT: aws-beta
      IMAGE_TAG: ${{ needs.variables.outputs.image_tag }}

  approve-deployment-to-prod:
    needs: [variables, approve-deployment-to-beta]
    uses: ./.github/workflows/sub_approve_deployment.yml
    secrets:
      KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN_STAGING }}
    with:
      KOSLI_HOST: ${{ needs.variables.outputs.kosli_host }}
      KOSLI_ORG: ${{ needs.variables.outputs.kosli_org }}
      KOSLI_ENVIRONMENT: aws-prod
      IMAGE_TAG: ${{ needs.variables.outputs.image_tag }}

  push-latest:
    needs: [variables, approve-deployment-to-prod]
    uses: ./.github/workflows/sub_push_latest.yml
    secrets:
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
    with:
      IMAGE_TAG: ${{ needs.variables.outputs.image_tag }}

